### ISSUE TITLE
Accept EOS files

### ISSUE THREAD

**Issue by echapon** [echapon/HiCharm2015#1]
ie swicth from "new TFIle()" to "TFile::Open()" when accessing onia trees

**Comment by stahlleiton** [comment]
I tried that but for some weird reason I get the following error:

cling::DynamicLibraryManager::loadLibrary(): libXrdUtils.so.1: cannot open shared object file: No such file or directory
Error in TInterpreter::TCling::AutoLoad: failure loading library libNetxNG.so for TNetXNGSystem
cling::DynamicLibraryManager::loadLibrary(): libXrdUtils.so.1: cannot open shared object file: No such file or directory
cling::DynamicLibraryManager::loadLibrary(): libXrdUtils.so.1: cannot open shared object file: No such file or directory
Error in TInterpreter::TCling::AutoLoad: failure loading library libNetxNG.so for TNetXNGFile
cling::DynamicLibraryManager::loadLibrary(): libXrdUtils.so.1: cannot open shared object file: No such file or directory

I am trying to debug it

**Comment by echapon** [comment]
1aadfd683d5ec34b89371093071aa24e3e3d2fcf enables reading files from EOS without error for me.
