### ISSUE TITLE
[very very low] plotting of PDFs

### ISSUE THREAD

**Issue by echapon** [echapon/HiCharm2015#10]
**DO NOT IMPLEMENT FOR NOW**

Improve / change the plotting of the PDFs for data fits to make it more similar to plots in the AN of 12-007? i.e. plot the sum of the background pdf and the different signal components.

ws->pdf("sigMassPDF")->plotOn(mframe,Name("CBPsi"),Components("signalCBpsi,BkgFunct"),LineColor(kOrange+2),LineStyle(7),LineWidth(3),Normalization(data->sumEntries(),RooAbsReal::NumEvent));
  ws->pdf("sigMassPDF")->plotOn(mframe,Name("GaussPsi"),Components("signalG1P,BkgFunct"),LineColor(kGreen+3),LineStyle(7),LineWidth(4),Normalization(data->sumEntries(),RooAbsReal::NumEvent));
where signalCBpsi and signalG1P are signal model for Psi2s

**Comment by stahlleiton** [comment]
see https://github.com/echapon/HiCharm2015/commit/063ba298bc26085458a8ac094387c157a2149868
