### ISSUE TITLE
[low] naming convention for background

### ISSUE THREAD

**Issue by echapon** [echapon/HiCharm2015#12]
Change FirstChebychev, SecondChebychev, ... to Chebychev1, Chebychev2, ... so that François can sort fits more easily :)

**Comment by stahlleiton** [comment]
see https://github.com/echapon/HiCharm2015/commit/edebb078d6dd6ecb674f5654048d74ca20d800bc

**Comment by FrancoisArleo** [comment]
Merci Andre1 :)

Le 29 mars 2016 à 18:54, Andre Stahl <notifications@github.com<mailto:notifications@github.com>> a écrit :

Closed #12https://github.com/echapon/HiCharm2015/issues/12.
