### ISSUE TITLE
[medium priority] Add centrality and filter efficiency weights to MC RooDatasets

### ISSUE THREAD

**Issue by stahlleiton** [echapon/HiCharm2015#4]
When dealing with MC OniaTrees (we can use DSName.find("MC") to know this), we will have to add the option in the tree2Dataset.C to include the weights of each tree corresponding to their filter efficiency \* NColl.

**Comment by echapon** [comment]
I confirm the "medium" priority :)

**Comment by jmartinb** [comment]
I will deal with this one

**Comment by jmartinb** [comment]
This is done
