### ISSUE TITLE
[low] Fix tail parameters using MC

### ISSUE THREAD

**Issue by stahlleiton** [echapon/HiCharm2015#5]
When fitting data using Crystalball, we should first extract the information from MC and use the corresponding alpha and n values to fix the tail parameters in data. This would require to either make a step where we fit MC every time we fit data, or fit the MC once and set the tail parameters in the input files (to avoid hard-coding it and then having issues when changing kinematic bins)

**Comment by echapon** [comment]
I prefer the second option (fit the MC, write the tail parameters into input files, and fit the data in a different pass). But this is not very high priority, for now taking some "reasonable" tail parameters is enough. It's more important to decide on the binning on the nominal signal and background shape.

**Comment by stahlleiton** [comment]
Well, we are already doing this so I will just close this one
