### ISSUE TITLE
[high?] Memory issues

### ISSUE THREAD

**Issue by stahlleiton** [echapon/HiCharm2015#6]
When running many fits in a single process (seems to be around 10 fits per core), the memory allocation explodes with the following error:

[#1] INFO:Minization -- RooMinuit::optimizeConst: activating const optimization
RooAbsTestStatistic::initSimMode: creating slave calculator #0 for state PbPb (84335 dataset entries)
[#1] INFO:Fitting -- RooAbsOptTestStatistic::ctor(PbPb) constructing test statistic for sub-range named MassWindow
[#1] INFO:Fitting -- RooAbsOptTestStatistic::ctor(PbPb) fixing interpretation of coefficients of any RooAddPdf to full domain of observables
RooAbsTestStatistic::initSimMode: creating slave calculator #1 for state PP (187722 dataset entries)
[#1] INFO:Fitting -- RooAbsOptTestStatistic::ctor(PP) constructing test statistic for sub-range named MassWindow
[#1] INFO:Fitting -- RooAbsOptTestStatistic::ctor(PP) fixing interpretation of coefficients of any RooAddPdf to full domain of observables
[#1] INFO:Fitting -- RooAbsTestStatistic::initSimMode: created 2 slave calculators.
terminate called after throwing an instance of 'RooFit::BidirMMapPipe_impl::BidirMMapPipeException'
  what():  fork: Cannot allocate memory

So, we should check if all objects are properly deleted and the memory is correctly managed with the RooWorkspace approach (maybe the global workspace is storing the info of the local workspaces used during the fits)

**Comment by echapon** [comment]
Looks like it's fixed after André's last commit 66d5e9bff5495717be4a03654fd422ccac4637cc. Closing now.
